primeraAppEnC#/Models/ErrorViewModel.cs
namespace primeraAppEnC_.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

primeraAppEnC#/Models/Persona.cs
using System.ComponentModel.DataAnnotations;

namespace primeraAppEnC_.Models
{
    public class Persona
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "El nombre es obligatorio")]
        public string Nombre { get; set; } = "";

        [Required(ErrorMessage = "Los apellidos son obligatorios")]
        public string Apellido { get; set; } = "";

        [Required(ErrorMessage = "El email es obligatorio")]
        public string Email { get; set; }= "";
    }
}

primeraAppEnC#/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using primeraAppEnC_.Models;
using System.Diagnostics;

namespace primeraAppEnC_.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

primeraAppEnC#/Controllers/PersonasController.cs
using Microsoft.AspNetCore.Mvc;
using primeraAppEnC_.Models;
using primeraAppEnC_.Data;



namespace primeraAppEnC_.Controllers
{
    public class PersonasController : Controller
    {   // Simulamos una base de datos en memoria con una lista de personas
        private readonly AppDbContext _context;

        public PersonasController(AppDbContext context)
        {
            _context = context;
        }
        // GET: Personas
        public IActionResult Index()
        {

            var personas = _context.Personas.ToList();
            return View(personas);
        }
        // GET: Personas/Create
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        // POST: Personas/Create
        [HttpPost]
        public IActionResult Create(Persona persona)
        {
            if (!ModelState.IsValid)
                return View(persona);

            _context.Personas.Add(persona);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }



    }
}

primeraAppEnC#/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bienvenido a la app de Alex</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
    <p>Para ir a la seccion de personas pulsa el enlace</p>
    <a asp-controller="Personas" asp-action="Index">
        Ir a Personas
    </a>
</div>

primeraAppEnC#/Views/Personas/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model primeraAppEnC_.Models.Persona

<h2>Nueva Persona</h2>

<form asp-action="Create" method="post">
    <div>
        <label>Nombre</label>
        <input asp-for="Nombre" />
    </div>

    <div>
        <label>Apellidos</label>
        <input asp-for="Apellido" />
    </div>
    <div>
        <label>Email</label>
        <input type="email" asp-for="Email" />
    </div>

    <button type="submit">Guardar</button>
</form>

<a asp-action="Index">Volver</a>

primeraAppEnC#/Views/Personas/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<primeraAppEnC_.Models.Persona>

<a asp-action="Create">Nueva persona</a>

<h1>Lista de personas</h1>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Apellidos</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var p in Model)
        {
            <tr>
                <td>@p.Id</td>
                <td>@p.Nombre</td>
                <td>@p.Apellido</td>
                <td>@p.Email</td>
            </tr>
        }
        <!--Si esta vacia la bd-->
        @if (!Model.Any())
        {
            <tr>
                <td colspan="4">No hay personas registradas</td>
            </tr>
        }
    </tbody>
</table>

primeraAppEnC#/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - primeraAppEnC_</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/primeraAppEnC_.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">primeraAppEnC_</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2026 - primeraAppEnC_ - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>